$(document).ready(function(){
    $(".conorpic").click(function(){
        $(".bridgecookiehidden").addClass("bridgecookiereveal");
    });	
    $(".conorspeechbub").click(function(){
        $(".menu1hidden").addClass("menu1clicked");
        $(".menu2hidden").addClass("menu2clicked");
        $(".menu3hidden").addClass("menu3clicked");
        $(".container").addClass("backgroundclicked");
        $("html").addClass("backgroundclicked");
        $(".conorarrow").fadeOut(1000);
        $(".bridgecookiehidden").fadeOut(1000);
        $(this).fadeOut(1000);
    });
    $(".menu1hidden").click(function(){
        $(".circle2").fadeOut(1000);
        $(".bio").toggleClass("biohidden");
});
    $(".menu2hidden").click(function(){
        $(".circle1").fadeOut(1000);
        $(".publications").toggleClass("publicationshidden");
});
    $(".menu3hidden").click(function(){
        $(".circle3").fadeOut(1000);
        $(".github").toggleClass("githubhidden");
});
});